---
# First, make sure that Jenkins is stopped before attempting to copy any job
# configuration files.
- include_tasks: "{{ jenkins_install_via }}/stop.yml"

- name: Job directories are present
  file:
    path: "{{ jenkins_home }}/jobs/{{ item }}"
    state: directory
    mode: 0777
  with_items: "{{ jenkins_jobs }}"

- name: Jobs are present
  copy:
    src: "{{ jenkins_source_dir_jobs }}/{{ item }}/config.xml"
    dest: "{{ jenkins_home }}/jobs/{{ item }}/config.xml"
    mode: 0777
  with_items: "{{ jenkins_jobs }}"
