---

- name: Job directories are present
  file:
    path: "{{ jenkins_home }}/jobs/{{ item }}"
    state: directory
    mode: 0777
  with_items: "{{ jenkins_jobs }}"

- name: Jobs are present
  copy:
    src: "{{ jenkins_source_dir_jobs }}/{{ item }}/config.xml"
    dest: "{{ jenkins_home }}/jobs/{{ item }}/config.xml"
    mode: 0777
  with_items: "{{ jenkins_jobs }}"

- name: get token for jenkins api
  uri:
    url: '{{ jenkins_url }}:{{ jenkins_port }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
    return_content: yes
    status_code: 200,404
  register: jenkins_token

- name: Reload Jenkins if crumb is enabled
  uri:
    url: "{{ jenkins_url }}:{{ jenkins_port }}/reload"
    method: POST
    status_code: 200,302
    headers:
      Jenkins-Crumb: "{{ jenkins_token.content.split(':')[1] }}"
  ignore_errors: yes
  when: jenkins_token.status == 200

- name: Reload Jenkins if crumb is disabled
  uri:
    url: "{{ jenkins_url }}:{{ jenkins_port }}/reload"
    method: POST
    status_code: 200,302
  ignore_errors: yes
  when: jenkins_token.status == 404
